language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: eJPirgfwgdDo35KNsQAvjy+Tvdg5aFTy/DiaoerLZx9Q52NjxckZ0Vqp9gTZl72fCGGVdyiXNRvFskiP2+P1SO6RspmafgsVnj15mK4BRN8GgEWv5lN5Op8xmDDm+qJ3WVHyNC+IUxqt6K8rHoD+ysFdpNk28ODWqJ00K0zVjeA13gnwVRhpjegkJXIFp0vUSkpZYeV3XDmyLSaPktcgp2Z8sKyW9lx3SLMvHmEYQx2iSYm/ECGigzm8Fq3iw1LTucSfMDm80yXxnzkpxwIjUBlwFRvFU7Yn8q+6FV9706iHKOoQX206OLBbzQfvbKsctBgku4jVZBroRQdWF3CmyE5SRkhGGB1NXLk4YzgkMwNkKuxmPAwZK8nd2dsaw21nmSbNQrBDWQszYRy8OwOx5czJY0XTrAGS6mxF13Zn7E+rj7kHWmWXCoInXp6/FlEKRyBBDARc+ATEbc/qAY4reaLk3xmbPA6h4EfjdvXe+JeekN0LrOQzRULK6SiBkYY+InMbVKyAjd4m23zXczkXJn5BWRSHZb5gDSlx1IDI5rTkY1Lk/zkAOmukNBlW0Glsod+rAJ2GjS5i4HBQ1DOLejou6qCLkWjIwYFcser/SDRgrchmXWURjOZ8XJr5aWA+6SU7kD+Gihil/xbvVpCCo20WVS+a0q1LunbTUxFLMCA=
  app: mommy-talks-app
  on:
    repo: anamika8/Mommy-Talks
